/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

/**
 *
 * @author samsung
 */
public class aahoSudoku extends javax.swing.JFrame {

    /**
     * Creates new form aahoSudoku
     */
    public aahoSudoku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        j6 = new javax.swing.JTextField();
        j7 = new javax.swing.JTextField();
        j8 = new javax.swing.JTextField();
        j9 = new javax.swing.JTextField();
        j10 = new javax.swing.JTextField();
        j11 = new javax.swing.JTextField();
        j12 = new javax.swing.JTextField();
        j13 = new javax.swing.JTextField();
        j14 = new javax.swing.JTextField();
        j15 = new javax.swing.JTextField();
        j16 = new javax.swing.JTextField();
        j17 = new javax.swing.JTextField();
        j18 = new javax.swing.JTextField();
        j19 = new javax.swing.JTextField();
        j20 = new javax.swing.JTextField();
        j21 = new javax.swing.JTextField();
        j22 = new javax.swing.JTextField();
        j23 = new javax.swing.JTextField();
        j24 = new javax.swing.JTextField();
        j25 = new javax.swing.JTextField();
        j26 = new javax.swing.JTextField();
        j27 = new javax.swing.JTextField();
        j28 = new javax.swing.JTextField();
        j29 = new javax.swing.JTextField();
        j30 = new javax.swing.JTextField();
        j31 = new javax.swing.JTextField();
        j32 = new javax.swing.JTextField();
        j33 = new javax.swing.JTextField();
        j34 = new javax.swing.JTextField();
        j35 = new javax.swing.JTextField();
        j36 = new javax.swing.JTextField();
        j37 = new javax.swing.JTextField();
        j38 = new javax.swing.JTextField();
        j39 = new javax.swing.JTextField();
        j40 = new javax.swing.JTextField();
        j41 = new javax.swing.JTextField();
        j42 = new javax.swing.JTextField();
        j43 = new javax.swing.JTextField();
        j44 = new javax.swing.JTextField();
        j45 = new javax.swing.JTextField();
        j46 = new javax.swing.JTextField();
        j47 = new javax.swing.JTextField();
        j48 = new javax.swing.JTextField();
        j49 = new javax.swing.JTextField();
        j50 = new javax.swing.JTextField();
        j51 = new javax.swing.JTextField();
        j52 = new javax.swing.JTextField();
        j53 = new javax.swing.JTextField();
        j54 = new javax.swing.JTextField();
        j55 = new javax.swing.JTextField();
        j56 = new javax.swing.JTextField();
        j57 = new javax.swing.JTextField();
        j58 = new javax.swing.JTextField();
        j59 = new javax.swing.JTextField();
        j60 = new javax.swing.JTextField();
        j61 = new javax.swing.JTextField();
        j62 = new javax.swing.JTextField();
        j63 = new javax.swing.JTextField();
        j64 = new javax.swing.JTextField();
        j65 = new javax.swing.JTextField();
        j66 = new javax.swing.JTextField();
        j67 = new javax.swing.JTextField();
        j68 = new javax.swing.JTextField();
        j69 = new javax.swing.JTextField();
        j70 = new javax.swing.JTextField();
        j71 = new javax.swing.JTextField();
        j72 = new javax.swing.JTextField();
        j73 = new javax.swing.JTextField();
        j74 = new javax.swing.JTextField();
        j75 = new javax.swing.JTextField();
        j76 = new javax.swing.JTextField();
        j77 = new javax.swing.JTextField();
        j78 = new javax.swing.JTextField();
        j79 = new javax.swing.JTextField();
        j80 = new javax.swing.JTextField();
        j81 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Sudoku");

        jButton1.setText("Create Sudoku");

        jButton2.setText("Solve Sudoku");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        j1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j1ActionPerformed(evt);
            }
        });

        j2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2ActionPerformed(evt);
            }
        });

        j3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j3ActionPerformed(evt);
            }
        });

        j4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });

        j5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j5ActionPerformed(evt);
            }
        });

        j6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j6ActionPerformed(evt);
            }
        });

        j7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j7ActionPerformed(evt);
            }
        });

        j8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j8ActionPerformed(evt);
            }
        });

        j9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j9ActionPerformed(evt);
            }
        });

        j10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j10ActionPerformed(evt);
            }
        });

        j11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j11ActionPerformed(evt);
            }
        });

        j12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j12ActionPerformed(evt);
            }
        });

        j13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j13ActionPerformed(evt);
            }
        });

        j14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j14ActionPerformed(evt);
            }
        });

        j15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j15ActionPerformed(evt);
            }
        });

        j16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j16ActionPerformed(evt);
            }
        });

        j17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j17ActionPerformed(evt);
            }
        });

        j18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j18ActionPerformed(evt);
            }
        });

        j19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j19ActionPerformed(evt);
            }
        });

        j20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j20ActionPerformed(evt);
            }
        });

        j21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j21ActionPerformed(evt);
            }
        });

        j22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j22ActionPerformed(evt);
            }
        });

        j23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j23ActionPerformed(evt);
            }
        });

        j24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j24ActionPerformed(evt);
            }
        });

        j25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j25ActionPerformed(evt);
            }
        });

        j26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j26ActionPerformed(evt);
            }
        });

        j27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j27ActionPerformed(evt);
            }
        });

        j28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j28ActionPerformed(evt);
            }
        });

        j29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j29ActionPerformed(evt);
            }
        });

        j30.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j30ActionPerformed(evt);
            }
        });

        j31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j31ActionPerformed(evt);
            }
        });

        j32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j32ActionPerformed(evt);
            }
        });

        j33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j33ActionPerformed(evt);
            }
        });

        j34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j34ActionPerformed(evt);
            }
        });

        j35.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j35ActionPerformed(evt);
            }
        });

        j36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j36ActionPerformed(evt);
            }
        });

        j37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j37ActionPerformed(evt);
            }
        });

        j38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j38ActionPerformed(evt);
            }
        });

        j39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j39ActionPerformed(evt);
            }
        });

        j40.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j40ActionPerformed(evt);
            }
        });

        j41.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j41ActionPerformed(evt);
            }
        });

        j42.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j42ActionPerformed(evt);
            }
        });

        j43.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j43ActionPerformed(evt);
            }
        });

        j44.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j44ActionPerformed(evt);
            }
        });

        j45.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j45ActionPerformed(evt);
            }
        });

        j46.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j46ActionPerformed(evt);
            }
        });

        j47.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j47ActionPerformed(evt);
            }
        });

        j48.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j48ActionPerformed(evt);
            }
        });

        j49.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j49ActionPerformed(evt);
            }
        });

        j50.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j50ActionPerformed(evt);
            }
        });

        j51.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j51ActionPerformed(evt);
            }
        });

        j52.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j52ActionPerformed(evt);
            }
        });

        j53.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j53ActionPerformed(evt);
            }
        });

        j54.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j54ActionPerformed(evt);
            }
        });

        j55.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j55ActionPerformed(evt);
            }
        });

        j56.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j56ActionPerformed(evt);
            }
        });

        j57.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j57ActionPerformed(evt);
            }
        });

        j58.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j58ActionPerformed(evt);
            }
        });

        j59.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j59ActionPerformed(evt);
            }
        });

        j60.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j60ActionPerformed(evt);
            }
        });

        j61.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j61ActionPerformed(evt);
            }
        });

        j62.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j62ActionPerformed(evt);
            }
        });

        j63.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j63ActionPerformed(evt);
            }
        });

        j64.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j64ActionPerformed(evt);
            }
        });

        j65.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j65ActionPerformed(evt);
            }
        });

        j66.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j66ActionPerformed(evt);
            }
        });

        j67.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j67ActionPerformed(evt);
            }
        });

        j68.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j68ActionPerformed(evt);
            }
        });

        j69.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j69ActionPerformed(evt);
            }
        });

        j70.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j70ActionPerformed(evt);
            }
        });

        j71.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j71ActionPerformed(evt);
            }
        });

        j72.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j72ActionPerformed(evt);
            }
        });

        j73.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j73ActionPerformed(evt);
            }
        });

        j74.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j74ActionPerformed(evt);
            }
        });

        j75.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j75ActionPerformed(evt);
            }
        });

        j76.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j76ActionPerformed(evt);
            }
        });

        j77.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j77ActionPerformed(evt);
            }
        });

        j78.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j78ActionPerformed(evt);
            }
        });

        j79.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j79ActionPerformed(evt);
            }
        });

        j80.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j80ActionPerformed(evt);
            }
        });

        j81.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        j81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j81ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(j46, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j37, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j29, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j38, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j39, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j40, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j41, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j42, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j43, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j44, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j45, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j47, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j48, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j49, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j50, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j51, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j52, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j53, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j54, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(j64, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j55, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j73, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j56, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j57, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j58, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j59, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j60, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j61, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j62, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j63, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j65, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j66, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j67, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j68, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j69, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j70, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j71, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j72, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(j74, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j75, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j76, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j77, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j78, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(j79, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j80, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(j81, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(10, 10, 10)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j39, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j41, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j42, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j43, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j44, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j45, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j46, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j47, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j48, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j49, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j51, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j52, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j53, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j54, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j55, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j56, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j57, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j58, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j59, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j60, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j61, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j62, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j63, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j64, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j65, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j66, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j67, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j68, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j69, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j70, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j71, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j72, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j73, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j74, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j75, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j76, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j77, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j78, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j79, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j80, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j81, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j14ActionPerformed
        sudokumatrix[1][4]= Integer.parseInt(j14.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j14ActionPerformed

    private void j15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j15ActionPerformed
       sudokumatrix[1][5]= Integer.parseInt(j15.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j15ActionPerformed

    private void j16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j16ActionPerformed
       sudokumatrix[1][6]= Integer.parseInt(j16.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j16ActionPerformed

    private void j17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j17ActionPerformed
        sudokumatrix[1][7]= Integer.parseInt(j17.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j17ActionPerformed

    private void j18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j18ActionPerformed
       sudokumatrix[1][8]= Integer.parseInt(j18.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j18ActionPerformed

    private void j19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j19ActionPerformed
        sudokumatrix[2][0]= Integer.parseInt(j19.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j19ActionPerformed

    private void j20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j20ActionPerformed
      sudokumatrix[2][1]= Integer.parseInt(j20.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_j20ActionPerformed

    private void j21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j21ActionPerformed
        sudokumatrix[2][2]= Integer.parseInt(j21.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j21ActionPerformed

    private void j22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j22ActionPerformed
      sudokumatrix[2][3]= Integer.parseInt(j22.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_j22ActionPerformed

    private void j23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j23ActionPerformed
       sudokumatrix[2][4]= Integer.parseInt(j23.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j23ActionPerformed

    private void j24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j24ActionPerformed
      sudokumatrix[2][5]= Integer.parseInt(j24.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_j24ActionPerformed

    private void j25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j25ActionPerformed
      sudokumatrix[2][6]= Integer.parseInt(j25.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_j25ActionPerformed

    private void j26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j26ActionPerformed
       sudokumatrix[2][7]= Integer.parseInt(j26.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j26ActionPerformed

    private void j27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j27ActionPerformed
      sudokumatrix[2][8]= Integer.parseInt(j27.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_j27ActionPerformed

    private void j28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j28ActionPerformed
       sudokumatrix[3][0]= Integer.parseInt(j28.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j28ActionPerformed

    private void j29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j29ActionPerformed
        sudokumatrix[3][1]= Integer.parseInt(j29.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j29ActionPerformed

    private void j30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j30ActionPerformed
        sudokumatrix[3][2]= Integer.parseInt(j30.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j30ActionPerformed

    private void j31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j31ActionPerformed
       sudokumatrix[3][3]= Integer.parseInt(j31.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j31ActionPerformed

    private void j32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j32ActionPerformed
       sudokumatrix[3][4]= Integer.parseInt(j32.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j32ActionPerformed

    private void j33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j33ActionPerformed
       sudokumatrix[3][5]= Integer.parseInt(j33.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j33ActionPerformed

    private void j34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j34ActionPerformed
       sudokumatrix[3][6]= Integer.parseInt(j34.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j34ActionPerformed

    private void j35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j35ActionPerformed
      sudokumatrix[3][7]= Integer.parseInt(j35.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_j35ActionPerformed

    private void j36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j36ActionPerformed
      sudokumatrix[3][8]= Integer.parseInt(j36.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_j36ActionPerformed

    private void j37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j37ActionPerformed
       sudokumatrix[4][0]= Integer.parseInt(j37.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j37ActionPerformed

    private void j38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j38ActionPerformed
      sudokumatrix[4][1]= Integer.parseInt(j38.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_j38ActionPerformed

    private void j39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j39ActionPerformed
       sudokumatrix[4][2]= Integer.parseInt(j39.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j39ActionPerformed

    private void j40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j40ActionPerformed
       sudokumatrix[4][3]= Integer.parseInt(j40.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j40ActionPerformed

    private void j41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j41ActionPerformed
       sudokumatrix[4][4]= Integer.parseInt(j41.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j41ActionPerformed

    private void j42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j42ActionPerformed
       sudokumatrix[4][5]= Integer.parseInt(j42.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j42ActionPerformed

    private void j43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j43ActionPerformed
       sudokumatrix[4][6]= Integer.parseInt(j43.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j43ActionPerformed

    private void j44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j44ActionPerformed
       sudokumatrix[4][7]= Integer.parseInt(j44.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j44ActionPerformed

    private void j45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j45ActionPerformed
        sudokumatrix[4][8]= Integer.parseInt(j45.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j45ActionPerformed

    private void j46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j46ActionPerformed
        sudokumatrix[5][0]= Integer.parseInt(j46.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j46ActionPerformed

    private void j47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j47ActionPerformed
        sudokumatrix[5][1]= Integer.parseInt(j47.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j47ActionPerformed

    private void j48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j48ActionPerformed
        sudokumatrix[5][2]= Integer.parseInt(j48.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j48ActionPerformed

    private void j49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j49ActionPerformed
        sudokumatrix[5][3]= Integer.parseInt(j49.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j49ActionPerformed

    private void j50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j50ActionPerformed
        sudokumatrix[5][4]= Integer.parseInt(j50.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j50ActionPerformed

    private void j51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j51ActionPerformed
        sudokumatrix[5][5]= Integer.parseInt(j51.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j51ActionPerformed

    private void j52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j52ActionPerformed
       sudokumatrix[5][6]= Integer.parseInt(j52.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j52ActionPerformed

    private void j53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j53ActionPerformed
       sudokumatrix[5][7]= Integer.parseInt(j53.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j53ActionPerformed

    private void j54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j54ActionPerformed
        sudokumatrix[5][8]= Integer.parseInt(j54.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j54ActionPerformed

    private void j55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j55ActionPerformed
        sudokumatrix[6][0]= Integer.parseInt(j55.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j55ActionPerformed

    private void j56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j56ActionPerformed
        sudokumatrix[6][1]= Integer.parseInt(j56.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j56ActionPerformed

    private void j57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j57ActionPerformed
        sudokumatrix[6][2]= Integer.parseInt(j57.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j57ActionPerformed

    private void j58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j58ActionPerformed
        sudokumatrix[6][3]= Integer.parseInt(j58.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j58ActionPerformed

    private void j59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j59ActionPerformed
       sudokumatrix[6][4]= Integer.parseInt(j59.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j59ActionPerformed

    private void j60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j60ActionPerformed
       sudokumatrix[6][5]= Integer.parseInt(j60.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j60ActionPerformed

    private void j61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j61ActionPerformed
        sudokumatrix[6][6]= Integer.parseInt(j61.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j61ActionPerformed

    private void j62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j62ActionPerformed
        sudokumatrix[6][7]= Integer.parseInt(j62.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j62ActionPerformed

    private void j63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j63ActionPerformed
        sudokumatrix[6][8]= Integer.parseInt(j63.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j63ActionPerformed

    private void j64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j64ActionPerformed
        sudokumatrix[7][0]= Integer.parseInt(j64.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j64ActionPerformed

    private void j65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j65ActionPerformed
       sudokumatrix[7][1]= Integer.parseInt(j65.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j65ActionPerformed

    private void j66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j66ActionPerformed
        sudokumatrix[7][2]= Integer.parseInt(j66.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j66ActionPerformed

    private void j67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j67ActionPerformed
        sudokumatrix[7][3]= Integer.parseInt(j67.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j67ActionPerformed

    private void j68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j68ActionPerformed
        sudokumatrix[7][4]= Integer.parseInt(j68.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j68ActionPerformed

    private void j69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j69ActionPerformed
        sudokumatrix[7][5]= Integer.parseInt(j69.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j69ActionPerformed

    private void j70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j70ActionPerformed
       sudokumatrix[7][6]= Integer.parseInt(j70.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j70ActionPerformed

    private void j71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j71ActionPerformed
       sudokumatrix[7][7]= Integer.parseInt(j71.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j71ActionPerformed

    private void j72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j72ActionPerformed
        sudokumatrix[7][8]= Integer.parseInt(j72.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j72ActionPerformed

    private void j73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j73ActionPerformed
       sudokumatrix[8][0]= Integer.parseInt(j73.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j73ActionPerformed

    private void j74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j74ActionPerformed
        sudokumatrix[8][1]= Integer.parseInt(j74.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j74ActionPerformed

    private void j75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j75ActionPerformed
       sudokumatrix[8][2]= Integer.parseInt(j75.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j75ActionPerformed

    private void j76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j76ActionPerformed
        sudokumatrix[8][3]= Integer.parseInt(j76.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j76ActionPerformed

    private void j77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j77ActionPerformed
        sudokumatrix[8][4]= Integer.parseInt(j77.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j77ActionPerformed

    private void j78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j78ActionPerformed
        sudokumatrix[8][5]= Integer.parseInt(j78.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j78ActionPerformed

    private void j79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j79ActionPerformed
        sudokumatrix[8][6]= Integer.parseInt(j79.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j79ActionPerformed

    private void j80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j80ActionPerformed
        sudokumatrix[8][7]= Integer.parseInt(j80.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j80ActionPerformed

    private void j81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j81ActionPerformed
        sudokumatrix[8][8]= Integer.parseInt(j81.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j81ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void j1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j1ActionPerformed
     sudokumatrix[0][0]= Integer.parseInt(j1.getText());   // TODO add your handling code here:
    }//GEN-LAST:event_j1ActionPerformed

    private void j2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2ActionPerformed
        sudokumatrix[0][1]= Integer.parseInt(j2.getText());
        System.out.println(j2.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j2ActionPerformed

    private void j3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j3ActionPerformed
       sudokumatrix[0][2]= Integer.parseInt(j3.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j3ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
       sudokumatrix[0][3]= Integer.parseInt(j4.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j4ActionPerformed

    private void j5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j5ActionPerformed
      sudokumatrix[0][4]= Integer.parseInt(j5.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_j5ActionPerformed

    private void j6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j6ActionPerformed
        sudokumatrix[0][5]= Integer.parseInt(j6.getText());// TODO add your handling code here:
    }//GEN-LAST:event_j6ActionPerformed

    private void j7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j7ActionPerformed
       sudokumatrix[0][6]= Integer.parseInt(j7.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j7ActionPerformed

    private void j8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j8ActionPerformed
       sudokumatrix[0][7]= Integer.parseInt(j8.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j8ActionPerformed

    private void j9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j9ActionPerformed
       sudokumatrix[0][8]= Integer.parseInt(j9.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j9ActionPerformed

    private void j10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j10ActionPerformed
       sudokumatrix[1][0]= Integer.parseInt(j10.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j10ActionPerformed

    private void j11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j11ActionPerformed
     sudokumatrix[1][1]= Integer.parseInt(j11.getText());   // TODO add your handling code here:
    }//GEN-LAST:event_j11ActionPerformed

    private void j12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j12ActionPerformed
       sudokumatrix[1][2]= Integer.parseInt(j12.getText()); // TODO add your handling code here:
    }//GEN-LAST:event_j12ActionPerformed

    private void j13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j13ActionPerformed
      sudokumatrix[1][3]= Integer.parseInt(j13.getText());  // TODO add your handling code here:
    }//GEN-LAST:event_j13ActionPerformed
int sudokumatrix[][]= new int[9][9];
int top[]=new int[81],count;
int stack[][] = new int[81][9];
void push(int s,int val)
{
    stack[s][++top[s]]=val;
}
int pop(int s)
{
    int aaho;
    aaho= stack[s][top[s]--];
    return aaho;
}

    boolean sudoku(int x,int y)
{
    if(x<9&&y<9)
    {
        if(sudokumatrix[x][y]==0)
        {
            all_possible_entries(x,y);
            while(top[x*9+y]>-1)
            {
                sudokumatrix[x][y]=pop(x*9+y);
                if(sudoku(x+(y+1)/9,(y+1)%9))
                    return true;
            }
            sudokumatrix[x][y]=0;
            return false;
        }
        return sudoku(x+(y+1)/9,(y+1)%9);
    }
    return false;
}
void all_possible_entries(int x,int y)
{
    int arr[]= new int[9];
    int i,j,bx,by;
    for(j=0;j<9;j++)
        arr[sudokumatrix[x][j]]=1;
    for(i=0;i<9;i++)
        arr[sudokumatrix[i][y]]=1;
    bx=x/3;
    by=y/3;
    for(i=bx*3;i<(bx+1)*3;i++)
        for(j=by*3;j<(by+1)*3;j++)
        arr[sudokumatrix[i][j]] = 1;
    for(i=1;i<10;i++)
        if(arr[i]==0)
        push(x*9+y,i);
}
/*void input()
{ 
    int i=0,j=0;
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j1.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j2.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j3.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j4.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j5.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j6.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j7.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j8.getText());
    sudokumatrix[i++][(j++)%9] = Integer.parseInt(j9.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j10.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j11.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j12.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j13.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j14.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j15.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j16.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j17.getText());
    sudokumatrix[i++][(j++)%9] = Integer.parseInt(j18.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j19.getText());
    sudokumatrix[i][(j++)%9] = Integer.parseInt(j20.getText());
}*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aahoSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aahoSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aahoSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aahoSudoku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aahoSudoku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j11;
    private javax.swing.JTextField j12;
    private javax.swing.JTextField j13;
    private javax.swing.JTextField j14;
    private javax.swing.JTextField j15;
    private javax.swing.JTextField j16;
    private javax.swing.JTextField j17;
    private javax.swing.JTextField j18;
    private javax.swing.JTextField j19;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j20;
    private javax.swing.JTextField j21;
    private javax.swing.JTextField j22;
    private javax.swing.JTextField j23;
    private javax.swing.JTextField j24;
    private javax.swing.JTextField j25;
    private javax.swing.JTextField j26;
    private javax.swing.JTextField j27;
    private javax.swing.JTextField j28;
    private javax.swing.JTextField j29;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j30;
    private javax.swing.JTextField j31;
    private javax.swing.JTextField j32;
    private javax.swing.JTextField j33;
    private javax.swing.JTextField j34;
    private javax.swing.JTextField j35;
    private javax.swing.JTextField j36;
    private javax.swing.JTextField j37;
    private javax.swing.JTextField j38;
    private javax.swing.JTextField j39;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j40;
    private javax.swing.JTextField j41;
    private javax.swing.JTextField j42;
    private javax.swing.JTextField j43;
    private javax.swing.JTextField j44;
    private javax.swing.JTextField j45;
    private javax.swing.JTextField j46;
    private javax.swing.JTextField j47;
    private javax.swing.JTextField j48;
    private javax.swing.JTextField j49;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j50;
    private javax.swing.JTextField j51;
    private javax.swing.JTextField j52;
    private javax.swing.JTextField j53;
    private javax.swing.JTextField j54;
    private javax.swing.JTextField j55;
    private javax.swing.JTextField j56;
    private javax.swing.JTextField j57;
    private javax.swing.JTextField j58;
    private javax.swing.JTextField j59;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j60;
    private javax.swing.JTextField j61;
    private javax.swing.JTextField j62;
    private javax.swing.JTextField j63;
    private javax.swing.JTextField j64;
    private javax.swing.JTextField j65;
    private javax.swing.JTextField j66;
    private javax.swing.JTextField j67;
    private javax.swing.JTextField j68;
    private javax.swing.JTextField j69;
    private javax.swing.JTextField j7;
    private javax.swing.JTextField j70;
    private javax.swing.JTextField j71;
    private javax.swing.JTextField j72;
    private javax.swing.JTextField j73;
    private javax.swing.JTextField j74;
    private javax.swing.JTextField j75;
    private javax.swing.JTextField j76;
    private javax.swing.JTextField j77;
    private javax.swing.JTextField j78;
    private javax.swing.JTextField j79;
    private javax.swing.JTextField j8;
    private javax.swing.JTextField j80;
    private javax.swing.JTextField j81;
    private javax.swing.JTextField j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
